name: CR

on:
  push:
    branches: [main, beta, alpha]

concurrency:
  group: "release"
  cancel-in-progress: true

permissions:
  id-token: write # to enable use of OIDC for npm provenance
  contents: write # to be able to publish a GitHub release
  issues: write # to be able to comment on released issues
  pull-requests: write # to be able to comment on released pull requests

jobs:
  release:
    runs-on: "ubuntu-latest"
    env:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: setup node
        uses: actions/setup-node@v4
        with:
          cache: "npm"
          node-version: 20

      - name: install dependencies
        run: npm ci

      - name: build
        run: npm run build

      - name: generate release
        run: npx semantic-release
